### ISSUE TITLE
Nexjts App Router Build Process with New Relic not working

### ISSUE THREAD

**Issue by mike-rambil** [newrelic/newrelic-node-examples#261] opened 2024-06-19 02:44 UTC
[NOTE]: # ( ^^ Provide a general summary of the issue in the title above. ^^ )

## Description

I followed the example from [this repo](https://github.com/newrelic/newrelic-node-examples/tree/58f760e828c45d90391bda3f66764d4420ba4990/nextjs-app-router) and my build is throwing error.

## Steps to Reproduce

I followed the example from [this repo](https://github.com/newrelic/newrelic-node-examples/tree/58f760e828c45d90391bda3f66764d4420ba4990/nextjs-app-router) and my build is throwing error.

- Added app name and license key in newrelic.js file 
- Added layout code (from the example)
- Changed package.json command

## Expected Behavior

build to be successful

## Relevant Logs / Console output
```
   Generating static pages (3/14) 
 ⚠ Sending SIGTERM signal to static worker due to timeout of 60 seconds. Subsequent errors may be a result of the worker exiting.
 ⚠ Restarted static page generation for /_not-found because it took more than 60 seconds
 ⚠ See more info here https://nextjs.org/docs/messages/static-page-generation-timeout
 ⚠ Restarted static page generation for /dashboard/barrel-fill-schedule because it took more than 60 seconds
 ⚠ Restarted static page generation for /dashboard/barrel-inventory/open-locations because it took more than 60 seconds
 ⚠ Restarted static page generation for /dashboard/barrel-inventory because it took more than 60 seconds
 ⚠ Restarted static page generation for /dashboard/barrel-receipts because it took more than 60 seconds
 ⚠ Restarted static page generation for /dashboard/barrel-receipts/purchase-order because it took more than 60 seconds
 ⚠ Restarted static page generation for /dashboard because it took more than 60 seconds
 ⚠ Restarted static page generation for /dashboard/quality-reporting because it took more than 60 seconds
 ⚠ Restarted static page generation for /dashboard/transfer-in-out because it took more than 60 seconds
 ⚠ Restarted static page generation for /dashboard/upcoming-schedule because it took more than 60 seconds
 ⚠ Restarted static page generation for / because it took more than 60 seconds
 ⚠ Sending SIGTERM signal to static worker due to timeout of 60 seconds. Subsequent errors may be a result of the worker exiting.
 ⚠ Restarted static page generation for /_not-found because it took more than 60 seconds
 ⚠ Restarted static page generation for /dashboard/barrel-fill-schedule because it took more than 60 seconds
 ⚠ Restarted static page generation for /dashboard/barrel-inventory/open-locations because it took more than 60 seconds
 ⚠ Restarted static page generation for /dashboard/barrel-inventory because it took more than 60 seconds
 ⚠ Restarted static page generation for /dashboard/barrel-receipts because it took more than 60 seconds
 ⚠ Restarted static page generation for /dashboard/barrel-receipts/purchase-order because it took more than 60 seconds
 ⚠ Restarted static page generation for /dashboard because it took more than 60 seconds
 ⚠ Restarted static page generation for /dashboard/quality-reporting because it took more than 60 seconds
 ⚠ Restarted static page generation for /dashboard/transfer-in-out because it took more than 60 seconds
 ⚠ Restarted static page generation for /dashboard/upcoming-schedule because it took more than 60 seconds
 ⚠ Restarted static page generation for / because it took more than 60 seconds
 ⚠ Sending SIGTERM signal to static worker due to timeout of 60 seconds. Subsequent errors may be a result of the worker exiting.

> Build error occurred
Error: Static page generation for /_not-found is still timing out after 3 attempts. See more info here https://nextjs.org/docs/messages/static-page-generation-timeout
    at onRestart (/github/workspace/node_modules/next/dist/build/index.js:297:27)
    at /github/workspace/node_modules/next/dist/lib/worker.js:95:40
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async /github/workspace/node_modules/next/dist/export/index.js:518:20
    at async Span.traceAsyncFn (/github/workspace/node_modules/next/dist/trace/trace.js:151:20)
    at async /github/workspace/node_modules/next/dist/export/index.js:516:24
    at async Promise.all (index 3)
    at async exportAppImpl (/github/workspace/node_modules/next/dist/export/index.js:508:21)
    at async /github/workspace/node_modules/next/dist/export/index.js:681:16
    at async Span.traceAsyncFn (/github/workspace/node_modules/next/dist/trace/trace.js:151:20)
    at async /github/workspace/node_modules/next/dist/build/index.js:1494:42
    at async Span.traceAsyncFn (/github/workspace/node_modules/next/dist/trace/trace.js:151:20)
    at async /github/workspace/node_modules/next/dist/build/index.js:1341:17
    at async Span.traceAsyncFn (/github/workspace/node_modules/next/dist/trace/trace.js:151:20)
    at async build (/github/workspace/node_modules/next/dist/build/index.js:373:9)
    at async main (/github/workspace/node_modules/next/dist/bin/next:155:5)

```
---End of Oryx build logs---
Oryx has failed to build the solution.
[NOTE]: # ( Please provide specifics of the local error logs, Browser Dev Tools console, etc. if appropriate and possible. )

## Your Environment

[TIP]:  # ( Include as many relevant details about your environment as possible. )

* ex: Browser name and version:
* ex: Operating System and version:

## Additional context

[TIP]:  # ( Add any other context about the problem here. )

**Comment by jsumners-nr** [comment] 2024-06-24 12:21
👋 thank you for the report. Please provide a [minimal reproducible example](https://en.wikipedia.org/wiki/Minimal_reproducible_example). Doing so will help us diagnose the issue. It should be the bare minimum code needed to trigger the issue, and easily runnable without any changes or extra code.

You may use a GitHub repository to host the code if it is too much to fit into a [code block](https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/creating-and-highlighting-code-blocks) (or two).

**Comment by bizob2828** [comment] 2024-09-03 17:39
I'm closing this because we didn't receive a repro case. @mike-rambil if you can provide the repro case, please reopen

**Closed by bizob2828** 2024-09-03 17:39 UTC
Labels: need-repro
